ci(check-release): check that extension has release/tag

diff --git a/.github/workflows/check-extensions.yml b/.github/workflows/check-extensions.yml
--- a/.github/workflows/check-extensions.yml
+++ b/.github/workflows/check-extensions.yml
@@ -97,3 +97,30 @@ jobs:
               exit 1
             fi
           fi
+  check-release:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check for release/tag
+        shell: bash
+        run: |
+          FILE="extensions/quarto-extensions.csv"
+          error=false
+          add_extension=$(gh pr view "${NUMBER}" --json files --jq ".files[] | select(.path == \"${FILE}\")")
+          if [[ -n "${add_extension}" ]]; then
+            gh pr diff ${NUMBER} --patch | awk '/\+\+\+ b\/extensions\/quarto-extensions\.csv/{flag=1; next} flag && /^\+/' | sed 's/^+//' > diff.patch
+            if [[ -s diff.patch ]]; then
+              while IFS=, read -r repo; do
+                repo=$(echo "$repo" | cut -d'/' -f1-2)
+                repo_release=$(gh repo view --json latestRelease "${repo}" --jq ".latestRelease")
+                if [[ -z "${repo_release}" ]]; then
+                  lineNumber=$(grep -n "${repo}" ${FILE} | cut -d: -f1)
+                  echo "::error file=${FILE},line=${lineNumber},endLine=${lineNumber}::Repository \"${repo}\" is missing release/tag!"
+                  error=true
+                fi
+              done < diff.patch
+            fi
+            if [[ "${error}" = true ]]; then
+              exit 1
+            fi
+          fi
